./script/generate migration utenti
./script/generate migration campagne
./script/generate migration causali
./script/generate migration modelli
./script/generate migration mod_pags
./script/generate migration destinazioni
./script/generate migration unita
./script/generate migration zone
./script/generate migration create_table
./script/generate migration agenti
./script/generate migration clienti
./script/generate migration fornitori
./script/generate migration vettori
./script/generate migration prodotti
./script/generate migration magazzino
./script/generate migration ordini
./script/generate migration dettagli_ordini
./script/generate migration subdettagli_ordini
./script/generate migration bolle
./script/generate migration dettagli_bolle
./script/generate migration subdettagli_bolle
./script/generate migration fatture
./script/generate migration dettagli_fatture
